name: mdthree_one
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.7
  flutter_animate: ^2.2.0
  auto_animated: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  dart_code_metrics: ^5.4.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
